`timescale 1ns/1ps

// Behavioral model matching capture_bram generated by Block Memory Generator.
// BMG address ports are byte addressed when Enable_32bit_Address is enabled.
module capture_bram_tdp_model (
  input  logic        clka,
  input  logic        ena,
  input  logic [3:0]  wea,
  input  logic [31:0] addra,
  input  logic [31:0] dina,
  output logic [31:0] douta,

  input  logic        clkb,
  input  logic        enb,
  input  logic [3:0]  web,
  input  logic [31:0] addrb,
  input  logic [31:0] dinb,
  output logic [31:0] doutb
);
  import logic_analyzer_pkg::*;

  logic [BRAM_DATA_WIDTH-1:0] mem [0:CAPTURE_DEPTH-1];

  wire [BRAM_ADDR_WIDTH-1:0] word_addr_a =
      addra[BRAM_ADDR_WIDTH+1:2];
  wire [BRAM_ADDR_WIDTH-1:0] word_addr_b =
      addrb[BRAM_ADDR_WIDTH+1:2];

  always_ff @(posedge clka) begin
    if (ena) begin
      douta <= mem[word_addr_a];

      for (int unsigned lane = 0; lane < 4; lane++) begin
        if (wea[lane])
          mem[word_addr_a][lane*8 +: 8] <= dina[lane*8 +: 8];
      end
    end
  end

  always_ff @(posedge clkb) begin
    if (enb) begin
      doutb <= mem[word_addr_b];

      for (int unsigned lane = 0; lane < 4; lane++) begin
        if (web[lane])
          mem[word_addr_b][lane*8 +: 8] <= dinb[lane*8 +: 8];
      end
    end
  end
endmodule

